use StomatoloskaOrdinacija;

insert into Pacijent values
(0,'Miloš','Ranković','1982-12-17','Kralja Petra 15','0692457869','2016-10-18',0,1,'nema'),
(0,'Ksenija','Drakula','1982-05-07','Požeška 8','0637285426','2017-03-29',0,1,'nema'),
(0,'Sara','Drakula','2012-01-15','Požeška 8','0637285426','2017-03-29',0,1,'nema'),
(0,'Sofija','Milošević','1995-12-28','Borska 13','0648236954','2015-07-12',0,1,'nema'),
(0,'Milorad','Šušić','1968-08-23','Kozjačka 19','0658217532','2014-11-28',0,1,'nema'),
(0,'Nikola','Milojković','1985-02-03','Đorđa Vajferta 33','0692514782','2016-05-02',0,1,'nema'),
(0,'Svetlana','Milojković','1987-08-17','Đorđa Vajferta 33','0642345782','2016-05-02',0,1,'nema'),
(0,'Marko','Guzina','2008-11-28','Dalmatinska 16','0641236951','2017-02-07',0,1,'nema'),
(0,'Dragana','Guzina','1970-01-22','Dalmatinska 16','0641528438','2017-02-07',0,1,'nema'),
(0,'Petar','Kovačević','1995-07-06','Sterijina','0642814756','2014-10-17',0,1,'nema');

insert into Zaposleni values
(0,'Dr.Mirjana','Perišić'),
(0,'Dr.Mirko','Popović'),
(0,'Marina','Ivanović');

insert into Tehnicar values
(2,52);

insert into Stomatolog values
(1,'Stalni radni odnos',73),
(3,'Praksa',0);

insert into Zub values
(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),
(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0);

insert into OblastIntervencije values
(0,'Konzervativno lecenje zuba'),
(0,'Oralna hirurgija'),
(0,'Opšte usluge'),
(0,'Protetika'),
(0,'Parodontalna terapija'),
(0,'Decija i preventivna stomatologija'),
(0,'Ortopedija vilica - fiksni aparati'),
(0,'Pokretni aparati');

insert into SpisakIntervencija values
(0,'Amalgamski ispun-jednopovršinski',1500,1),
(0,'Amalgamski ispun-dvopovršinski',2000,1),
(0,'Amalgamski ispun-tropovršinski',2200,1),
(0,'Kompozitni ispun-jednopovršinski',2400,1),
(0,'Kompozitni ispun-dvopovršinski',2800,1),
(0,'Kompozitni ispun-tropovršinski',3500,1),
(0,'Indirektno prekrivanje pulpe',1300,1),
(0,'Direktno prekrivanje pulpe',1300,1),
(0,'Ponavljanje leka',0,1),
(0,'Vitalna amputacija jednokanalnog zuba',0,1),
(0,'Vitalna amputacija višekanalnog zuba',0,1),
(0,'Vitalna ekstirpacija jednokanalnog zuba',3000,1),
(0,'Vitalna ekstirpacija višekanalnog zuba',3500,1),
(0,'Mortalna amputacija',2000,1),
(0,'Mortalna ekstirpacija jednokanalnog zuba',3000,1),
(0,'Mortalna ekstirpacija dvokanalnog zuba',3500,1),
(0,'Mortalna ekstirpacija trokanalnog zuba',3500,1),
(0,'Lecenje gangrene',4800,1),
(0,'Uklanjanje kanalnog punjenja',4000,1),
(0,'Uklanjanje stranog tela iz kanala korena zuba',0,1),
(0,'Helio nadogradnja',4000,1),
(0,'Inlej metalni',0,1),
(0,'Inlej keramicki',0,1),
(0,'Parapulparni kocic (po komadu)',0,1),
(0,'Lokalna anestezija',0,2),
(0,'Rutinsko vadenje zuba',2100,2),
(0,'Hirurško vadenje zuba',12400,2),
(0,'Hirurško vadenje impaktiranog zuba',12400,2),
(0,'Resekcija zuba',12400,2),
(0,'Disekcija zuba',0,2),
(0,'Cistektomija',12400,2),
(0,'Incizija apscesa',3300,2),
(0,'Hemostaza mehanicka',0,2),
(0,'Biološka hemostaza',0,2),
(0,'Terapija alveolita (po seansi)',0,2),
(0,'Soluks lampa (po seansi)',0,2),
(0,'Operacija frenuluma',4200,2),
(0,'Nivelacija grebena',0,2),
(0,'Produbljivanje forniksa',0,2),
(0,'Hirurško zatvaranje sinusa',8800,2),
(0,'Implant jednofazni',500,2),
(0,'Implant dvofazni',600,2),
(0,'RTG snimak',0,3),
(0,'Imedijatna proteza',33000,4),
(0,'Parcijalna akrilatna proteza',31000,4),
(0,'Totalna proteza',37200,4),
(0,'Totalna proteza sa metalnom bazom',49600,4),
(0,'Parcijalna skeletirana proteza',49600,4),
(0,'Ugradnja atecmena (par)',12400,4),
(0,'Žabica',4400,4),
(0,'Direktno podlaganje proteza',5500,4),
(0,'Indirektno podlaganje proteza',11000,4),
(0,'Reraratura proteze',3700,4),
(0,'Zaštitna krunica',1300,4),
(0,'Privremeni most (po clanu)',0,4),
(0,'Skidanje krunice',0,4),
(0,'Džeket kruna',0,4),
(0,'Metalokermicka krunica na leguri od celika',12400,4),
(0,'Metalokeramicka krunica na leguri od titanijuma (otisak)',16500,4),
(0,'Bezmetalna keramika',24200,4),
(0,'Faseta od estetskog materijala',4000,4),
(0,'Fasetirana krunica',0,4),
(0,'Teleskop krunica',0,4),
(0,'Livena krunica',0,4),
(0,'Livena nadogradnja',4800,4),
(0,'Logan zub i fabricki kocic',4800,4),
(0,'Uklanjanje kamenca',2400,5),
(0,'Tuširanje desni',0,5),
(0,'Obrada gingivalnog dzepa LALdexamethason',1300,5),
(0,'Obrada parodoncijuma po zubu',4400,5),
(0,'Hirurška obrada parodoncijuma sa koštanim implantom',0,5),
(0,'Kauterizacija papile',0,5),
(0,'Pakovanje desni',0,5),
(0,'Zalivanje fisura',1500,6),
(0,'Uklanjanje mekih naslaga',700,6),
(0,'Impregacija zuba pastama natrijum fluorida',700,6),
(0,'Fiksni aparat metalne bravice',80600,7),
(0,'Ploca sa šrafom i pokretnim elementima',31000,8),
(0,'Bimaksilarni aparati-monoblok',33000,8),
(0,'Vestibularna ploca',10500,8),
(0,'Bradna kapa',0,8),
(0,'skidanje konaca',0,2),
(0,'konsultativni pregled',1300,3),
(0,'ekstrakcija mlecnih zuba sa anestezijom',2200,2),
(0,'REDOVNA KONTROLA SA CZK',1300,3),
(0,'PKK',0,1),
(0,'Cem. nad.',0,4),
(0,'Cem. kruna',0,4),
(0,'Predaja proteze',0,4),
(0,'Kontrola prot.rada',0,4),
(0,'Promena leka',0,1),
(0,'Izbeljivanje zuba po vilici',12400,1),
(0,'cirkumcizija',2200,2),
(0,'Drenaža',0,1),
(0,'Kontrola sa czk',1300,1),
(0,'alvogyl',0,2),
(0,'Izbeljivanje po zubu',4400,1),
(0,'Bioptron 10 seansi',4400,5),
(0,'Vadjenje mlecnog zuba',1300,6),
(0,'Korektura proteze',0,4),
(0,'Skinut fiksni aparat',0,7),
(0,'Cirkon',2500,1),
(0,'glass jonomer ispun',2000,1),
(0,'Kontrola ort.aparata',0,8),
(0,'Kontrola fiksnog aparata',0,7),
(0,'Animacija',0,6),
(0,'Cementna plomba',0,1),
(0,'Preventivno plombiranje',2000,6),
(0,'Lecenje kanala i plomba',3000,6),
(0,'Dyract - jednopovršinski',0,1),
(0,'Dyract - dvopovršinski',0,1),
(0,'zastita zubnih vratova',1300,1),
(0,'Splint',6100,8),
(0,'Glassionomer ispun na mlecnom zubu',2000,6),
(0,'Amalgamski ispun na mlecnom zubu',2000,6),
(0,'Tooth mousse pasta',2600,1),
(0,'hirurško uklanjanje papiloma',3300,2),
(0,'Sokle',2500,8),
(0,'Fiksni aparat keramicke bravice',105400,7),
(0,'kontrola',500,8),
(0,'kontrola',1000,7),
(0,'Folija dvostruka',11000,7),
(0,'tvin blok',55000,8),
(0,'Folija duplo livena',8250,7),
(0,'folija obicna',7150,7),
(0,'trijaž',2400,1),
(0,'Inman proteza',38500,8),
(0,'Invizalajn',12400,7),
(0,'Analiza',6100,7),
(0,'Retenciona folija',6100,7),
(0,'Ploca za dezartikulaciju',6600,8),
(0,'Palatalbar',12400,7),
(0,'reparatura',5500,8),
(0,'HIRAX',31000,8),
(0,'Fiksni ritejner',12400,7),
(0,'DURASOFT FOLIJA',6100,8),
(0,'gel za beljenje',3600,1),
(0,'Kompozitna kruna',6100,4),
(0,'Kompozitni inlej',5000,1),
(0,'Keramicki inlej',9900,4),
(0,'Miofunkcionalni aparat',15000,8);
-- (0,'relyx fiberpost',,helio nad.),
-- (0,'frc kocic',,glass jon),
-- (0,'STOMATOLOSKI PREGLED',,ANIMACIJA),

insert into Zahvat values
(0,'2016-10-18',1,73,15,1,null),
(0,'2016-10-18',1,73,10,1,null),
(0,'2017-03-29',2,50,2,null,2),
(0,'2017-03-29',3,67,5,3,null),
(0,'2017-05-18',3,67,12,3,null),
(0,'2017-05-19',3,115,1,1,null),
(0,'2017-05-19',3,115,2,1,null),
(0,'2015-07-12',4,68,8,3,null),
(0,'2014-11-28',5,119,null,null,2),
(0,'2016-07-28',5,113,null,null,2),
(0,'2016-05-02',6,55,16,1,2),
(0,'2016-05-02',7,83,5,1,null),
(0,'2016-05-02',7,83,8,1,null),
(0,'2017-12-08',7,98,15,1,null),
(0,'2017-02-07',8,85,3,1,null),
(0,'2017-02-07',9,140,30,1,null),
(0,'2014-10-17',10,118,null,1,2);

insert into Stolica values
(0,10),(0,11);

insert into Obavlja values
(1,1),(2,1),(3,2),(4,2),(5,2),(6,1),(7,2),(8,2),(9,1),(10,1),(11,2),(12,2),(13,2),(14,1);

insert into ZatecenoStanje values
(1,'frakturiran zub','karijes prvog stepena (površni)','zdrav, prisutan zub','zdrav, prisutan zub',
	'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','implantat','karijes drugog stepena (duboki)','karijes prvog stepena (površni)',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'karijes drugog stepena (duboki)','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub'),
(2,'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
	'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','karijes drugog stepena (duboki)','karijes prvog stepena (površni)',
    'pulpitis zuba','zdrav, prisutan zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub'),
(3,'zub u nicanju','mlecni zub','mlecni zub','mlecni zub',
	'mlecni zub','mlecni zub','mlecni zub','mlecni zub',
    'mlecni zub','mlecni zub','mlecni zub','mlecni zub',
    'zub u nicanju','zub u nicanju','izvadjen zub','izvadjen zub',
    'mlecni zub','mlecni zub','zub u nicanju','zub u nicanju',
    'mlecni zub','zub u nicanju','mlecni zub','zub u nicanju',
    'mlecni zub','zub u nicanju','mlecni zub','zub u nicanju',
    'zub u nicanju','zub u nicanju','mlecni zub','mlecni zub'),
(4,'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
	'izvadjen zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','izlecen zub','karijes prvog stepena (površni)',
    'karijes prvog stepena (površni)','zdrav, prisutan zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub',
    'zdrav, prisutan zub','izlecen zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zub u lecenju','zdrav, prisutan zub','zub u lecenju','zdrav, prisutan zub'),
(5,'izvadjen zub','zdrav, prisutan zub','izvadjen zub','izvadjen zub',
	'izvadjen zub','izvadjen zub','izvadjen zub','izvadjen zub',
    'izvadjen zub','izvadjen zub','izlecen zub','karijes prvog stepena (površni)',
    'karijes prvog stepena (površni)','izvadjen zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','izvadjen zub','zub u nicanju','izvadjen zub',
    'izvadjen zub','izlecen zub','izvadjen zub','izvadjen zub',
    'izvadjen zub','izvadjen zub','izvadjen zub','izvadjen zub',
    'zub u lecenju','koren zuba','zub u lecenju','koren zuba'),
(6,'zdrav, prisutan zub','plomba','zdrav, prisutan zub','zdrav, prisutan zub',
	'izvadjen zub','zdrav, prisutan zub','zdrav, prisutan zub','plomba',
    'zdrav, prisutan zub','zdrav, prisutan zub','izlecen zub','karijes drugog stepena (duboki)',
    'karijes prvog stepena (površni)','zdrav, prisutan zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub',
    'plomba','izlecen zub','zdrav, prisutan zub','periodontitis',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zub u lecenju','frakturiran zub','frakturiran zub','zdrav, prisutan zub'),
(7,'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
	'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','krunica zuba','implantat',
    'pulpitis zuba','zdrav, prisutan zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'implantat','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub'),
(8,'zdrav, prisutan zub','mlecni zub','zdrav, prisutan zub','mlecni zub',
	'mlecni zub','mlecni zub','mlecni zub','mlecni zub',
    'zdrav, prisutan zub','mlecni zub','mlecni zub','mlecni zub',
    'zub u nicanju','zub u nicanju','izvadjen zub','izvadjen zub',
    'zdrav, prisutan zub','mlecni zub','zub u nicanju','zub u nicanju',
    'zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub','zub u nicanju',
    'mlecni zub','zub u nicanju','zdrav, prisutan zub','zub u nicanju',
    'zub u nicanju','zub u nicanju','zdrav, prisutan zub','mlecni zub'),
(9,'zub u lecenju','zub u lecenju','zdrav, prisutan zub','zdrav, prisutan zub',
	'zdrav, prisutan zub','izlecen zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','plomba','izlecen zub',
    'pulpitis zuba','zdrav, prisutan zub','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'gangrena pulpe','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','izlecen zub','izlecen zub'),
(10,'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
	'izvadjen zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','izlecen zub','zdrav, prisutan zub',
    'karijes prvog stepena (površni)','karijes prvog stepena (površni)','zdrav, prisutan zub','izvadjen zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zub u nicanju','karijes prvog stepena (površni)',
    'zdrav, prisutan zub','izlecen zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub','zdrav, prisutan zub',
    'karijes prvog stepena (površni)','zdrav, prisutan zub','karijes prvog stepena (površni)','karijes prvog stepena (površni)');

insert into Materijal values
(0,'Amalgam I'),
(0,'Amalgam II'),
(0,'Amalgam III'),
(0,'Helio plombe'),
(0,'Kerr'),
(0,'Kalcijum-Hidroksid'),
(0,'Endometazon'),
(0,'Gutaperka poeni'),
(0,'Cink-oksid fosfatni cement'),
(0,'ZOOK'),
(0,'Alginat'),
(0,'Ksantopren'),
(0,'Cink-oksid eugenol pasta'),
(0,'Optozil'),
(0,'Retrargin'),
(0,'Konac za retrakciju gingive'),
(0,'Tubulicid'),
(0,'Roze vosak'),
(0,'Bazne ploce'),
(0,'Autopolimerizujuci akrilat'),
(0,'Alabaster gips'),
(0,'Plavi gips'),
(0,'Hirurška igla'),
(0,'Hirurški konac'),
(0,'Skalpeli'),
(0,'Hirurška rukavice'),
(0,'Hirurške kape'),
(0,'Hirurške maske'),
(0,'Hirurške kaljace'),
(0,'Biološki materijal'),
(0,'Hemijski materijal'),
(0,'Resorptivne membrane'),
(0,'Neresorptivne membrane'),
(0,'Kausticna sredstva'),
(0,'Vazokonstriktorna sredstva'),
(0,'Želatinski preparati'),
(0,'Hipertonicni rastvori'),
(0,'Antifibrinoliticna sredstva'),
(0,'Vitamini'),
(0,'Trombinski preparati'),
(0,'Fibrinski preparati'),
(0,'Pasta za punjenje desni'),
(0,'Pasta za uklanjanje mekih naslaga i poliranje zuba'),
(0,'Pomocna sredstva za parodontološke tretmane'),
(0,'Antibiotici'),
(0,'Analgetici'),
(0,'Anestetici'),
(0,'Kortikosteroidi'),
(0,'Oralni antiseptici'),
(0,'Asepsol'),
(0,'Vaterolne'),
(0,'Alkohol'),
(0,'Vodonik-peroksid'),
(0,'Sisaljke'),
(0,'Plasticne caše'),
(0,'Jodoform prah'),
(0,'Hlor-Fenol-Kamfor'),
(0,'Špricevi 2ml'),
(0,'Igle male'),
(0,'Igle velike'),
(0,'Kavipran'),
(0,'nerv igle'),
(0,'ker igle'),
(0,'turbinski boreri'),
(0,'boreri za kolenjak'),
(0,'gumice za poliranje'),
(0,'cetkice'),
(0,'Glassionomer cement za cementiranje'),
(0,'Artikulacioni papir'),
(0,'Citodur'),
(0,'Aktivator'),
(0,'Alkohol');

insert into Koristi values
(1,1),(2,2),(3,3),(69,15),
(107,1),(107,2),(107,3),(107,4),
(108,1),(108,2),(108,3),(108,4),
(109,1),(109,2),(109,3),(109,4);
